### ISSUE TITLE
Weavy has no construct signatures

### ISSUE THREAD

**Issue by tranphita** [weavy/weavy-uikit-web#1]
After installing npm install @weavy/uikit-web and setting up the service as described in the guide https://www.weavy.com/docs/frameworks/angular#install-uikit-web, I encountered the following error:
"This expression is not constructable.
Type 'typeof import(".../node_modules/@weavy/uikit-web/dist/types/index")' has no construct signatures

![error](https://github.com/weavy/weavy-uikit-web/assets/25834938/fb2a8f04-9fbc-4ad5-97ad-eb72f54c6d35)

**Comment by klasjersevi** [comment]
Thanks for the report. This has been changed to a named import.
```js
import { Weavy } from "@weavy/uikit-web";
```

We will update the documentation. Sorry for the inconvenience.
